name: Deploy Nginx to Server

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Install Nginx
      run: |
        # Install Nginx using your package manager
        sudo apt-get update
        sudo apt-get install -y nginx
        
    - name: Start Nginx
      run: |
        # Start Nginx service
        sudo systemctl start nginx
